"""add user column to control access

Revision ID: 3210fe23473d
Revises: a6a3e56d3f52
Create Date: 2026-06-28 17:40:06.206621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3210fe23473d"
down_revision: Union[str, None] = "a6a3e56d3f52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "access_allowed",
            sa.Boolean(),
            nullable=True,
        ),
    )

    op.execute("""
        UPDATE users
        SET access_allowed = TRUE
        """)

    op.alter_column(
        "users",
        "access_allowed",
        nullable=False,
        server_default=sa.false(),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "access_allowed")
    # ### end Alembic commands ###
