"""link system records to savings investments

Revision ID: 2518006cd411
Revises: cebddc9aa48b
Create Date: 2026-07-13 22:06:29.706106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2518006cd411"
down_revision: Union[str, None] = "cebddc9aa48b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expense", sa.Column("savings_investment_id", sa.BigInteger(), nullable=True)
    )
    op.create_unique_constraint(
        "uq_expense_savings_investment", "expense", ["savings_investment_id"]
    )
    op.create_foreign_key(
        "fk_expense_savings_investment_id",
        "expense",
        "savings_investment",
        ["savings_investment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "income", sa.Column("savings_investment_id", sa.BigInteger(), nullable=True)
    )
    op.create_unique_constraint(
        "uq_income_savings_investment", "income", ["savings_investment_id"]
    )
    op.create_foreign_key(
        "fk_income_savings_investment_id",
        "income",
        "savings_investment",
        ["savings_investment_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_income_savings_investment_id", "income", type_="foreignkey")
    op.drop_constraint("uq_income_savings_investment", "income", type_="unique")
    op.drop_column("income", "savings_investment_id")
    op.drop_constraint(
        "fk_expense_savings_investment_id", "expense", type_="foreignkey"
    )
    op.drop_constraint("uq_expense_savings_investment", "expense", type_="unique")
    op.drop_column("expense", "savings_investment_id")
    # ### end Alembic commands ###
