"""savings and investments

Revision ID: 15e12927e8ee
Revises: cc8155c55dbd
Create Date: 2026-07-12 21:06:41.024956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "15e12927e8ee"
down_revision: Union[str, None] = "cc8155c55dbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "savings_investment",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column(
            "available_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("savings_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "investment_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("family_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"], ["family.id"], name="fk_savings_investment_family_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "family_id", "year", "month", name="uq_savings_investment_family_year_month"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("savings_investment")
    # ### end Alembic commands ###
