"""add currency_type model

Revision ID: b2f5a53143e2
Revises: 8ca829c0170e
Create Date: 2026-07-21 21:31:29.146125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b2f5a53143e2"
down_revision: Union[str, None] = "8ca829c0170e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_type",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("symbol", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_currency_type_code"),
    )
    op.bulk_insert(
        sa.table(
            "currency_type",
            sa.column("id", sa.BigInteger()),
            sa.column("code", sa.String(length=3)),
            sa.column("symbol", sa.String(length=5)),
            sa.column("name", sa.String(length=50)),
        ),
        [
            {"id": 1, "code": "EUR", "symbol": "€", "name": "Euro"},
            {"id": 2, "code": "USD", "symbol": "US$", "name": "US Dollar"},
            {"id": 3, "code": "CAD", "symbol": "CA$", "name": "Canadian Dollar"},
            {"id": 4, "code": "CNY", "symbol": "CN¥", "name": "Chinese Yuan"},
            {"id": 5, "code": "JPY", "symbol": "JP¥", "name": "Japanese Yen"},
            {"id": 6, "code": "MXN", "symbol": "MX$", "name": "Mexican Peso"},
            {"id": 7, "code": "VES", "symbol": "Bs.", "name": "Venezuelan Bolívar"},
            {"id": 8, "code": "GBP", "symbol": "£", "name": "British Pound"},
            {"id": 9, "code": "CHF", "symbol": "CHF", "name": "Swiss Franc"},
            {"id": 10, "code": "COP", "symbol": "COL$", "name": "Colombian Peso"},
        ],
    )
    op.add_column(
        "family", sa.Column("currency_type_id", sa.BigInteger(), nullable=True)
    )
    op.execute(sa.text("""
            UPDATE family
            SET currency_type_id = 1
            WHERE currency_type_id IS NULL
            """))
    op.alter_column(
        "family",
        "currency_type_id",
        existing_type=sa.BigInteger(),
        nullable=False,
    )
    op.create_foreign_key(
        "fk_family_currency_type_id",
        "family",
        "currency_type",
        ["currency_type_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_family_currency_type_id", "family", type_="foreignkey")
    op.drop_column("family", "currency_type_id")
    op.drop_table("currency_type")
    # ### end Alembic commands ###
