"""add constraints

Revision ID: cebddc9aa48b
Revises: 15e12927e8ee
Create Date: 2026-07-13 17:35:19.144146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cebddc9aa48b"
down_revision: Union[str, None] = "15e12927e8ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category", sa.Column("normalized_name", sa.String(), nullable=False))
    op.create_unique_constraint(
        "uq_category_family_record_type_normalized_name",
        "category",
        ["family_id", "record_type_id", "normalized_name"],
    )
    op.create_unique_constraint(
        "uq_family_members_user_id", "family_members", ["user_id"]
    )
    op.drop_constraint(op.f("unique_record_type_name"), "record_type", type_="unique")
    op.create_unique_constraint("uq_record_type_name", "record_type", ["name"])
    op.drop_constraint(op.f("role_name_key"), "role", type_="unique")
    op.create_unique_constraint("uq_role_name", "role", ["name"])
    op.drop_constraint(op.f("users_clerk_id_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_unique_constraint(
        "uq_users_clerk_id_email", "users", ["clerk_id", "email"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_clerk_id_email", "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("users_clerk_id_key"),
        "users",
        ["clerk_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("uq_role_name", "role", type_="unique")
    op.create_unique_constraint(
        op.f("role_name_key"), "role", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint("uq_record_type_name", "record_type", type_="unique")
    op.create_unique_constraint(
        op.f("unique_record_type_name"),
        "record_type",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("uq_family_members_user_id", "family_members", type_="unique")
    op.drop_constraint(
        "uq_category_family_record_type_normalized_name", "category", type_="unique"
    )
    op.drop_column("category", "normalized_name")
    # ### end Alembic commands ###
