"""income and expeses

Revision ID: 999f2e6d53fc
Revises: ef6f641febb7
Create Date: 2026-07-07 12:52:49.735892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "999f2e6d53fc"
down_revision: Union[str, None] = "ef6f641febb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("family_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.id"], name="fk_expense_category_id"
        ),
        sa.ForeignKeyConstraint(
            ["family_id"], ["family.id"], name="fk_expense_family_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "income",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("family_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.id"], name="fk_income_category_id"
        ),
        sa.ForeignKeyConstraint(
            ["family_id"], ["family.id"], name="fk_income_family_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expense_item",
        sa.Column("product", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expense_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.id"], name="fk_expense_item_category_id"
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"], ["expense.id"], name="fk_expense_item_expense_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expense_item")
    op.drop_table("income")
    op.drop_table("expense")
    # ### end Alembic commands ###
