"""add unique constraint to record type name

Revision ID: ac09d6a73346
Revises: 999f2e6d53fc
Create Date: 2026-07-11 13:43:39.212584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ac09d6a73346"
down_revision: Union[str, None] = "999f2e6d53fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_record_type_name", "record_type", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_record_type_name", "record_type", type_="unique")
    # ### end Alembic commands ###
