"""add record types table

Revision ID: 2cd6190e5222
Revises: 67dfe9cdd8de
Create Date: 2026-06-25 16:09:01.554395

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2cd6190e5222"
down_revision: Union[str, None] = "67dfe9cdd8de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "record_types",
        sa.Column("record_type", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.bulk_insert(
        sa.table(
            "record_types",
            sa.column("id", sa.BigInteger()),
            sa.column("record_type", sa.String()),
        ),
        [
            {"id": 1, "record_type": "Expenses"},
            {"id": 2, "record_type": "Income"},
        ],
    )

    op.add_column(
        "categories",
        sa.Column("record_type_id", sa.BigInteger(), nullable=True),
    )

    op.execute("""
        UPDATE categories
        SET record_type_id = 1
        WHERE record_type_id IS NULL
        """)

    op.alter_column(
        "categories",
        "record_type_id",
        nullable=False,
    )

    op.create_foreign_key(
        "fk_categories_record_type_id",
        "categories",
        "record_types",
        ["record_type_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_categories_record_type_id", "categories", type_="foreignkey")
    op.drop_column("categories", "record_type_id")
    op.drop_table("record_types")
    # ### end Alembic commands ###
