"""add set null to category foreign keys

Revision ID: cc8155c55dbd
Revises: ac09d6a73346
Create Date: 2026-07-11 13:46:29.892062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cc8155c55dbd"
down_revision: Union[str, None] = "ac09d6a73346"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_expense_category_id"), "expense", type_="foreignkey")
    op.create_foreign_key(
        "fk_expense_category_id",
        "expense",
        "category",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        op.f("fk_expense_item_category_id"), "expense_item", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_expense_item_category_id",
        "expense_item",
        "category",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(op.f("fk_income_category_id"), "income", type_="foreignkey")
    op.create_foreign_key(
        "fk_income_category_id",
        "income",
        "category",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_income_category_id", "income", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_income_category_id"), "income", "category", ["category_id"], ["id"]
    )
    op.drop_constraint(
        "fk_expense_item_category_id", "expense_item", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_expense_item_category_id"),
        "expense_item",
        "category",
        ["category_id"],
        ["id"],
    )
    op.drop_constraint("fk_expense_category_id", "expense", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_expense_category_id"), "expense", "category", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###
