"""add new models: family, user, family members and role

Revision ID: a6a3e56d3f52
Revises: 2cd6190e5222
Create Date: 2026-06-27 15:41:06.406454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a6a3e56d3f52"
down_revision: Union[str, None] = "2cd6190e5222"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.bulk_insert(
        sa.table(
            "role",
            sa.column("id", sa.BigInteger()),
            sa.column("name", sa.String()),
        ),
        [
            {"id": 1, "name": "Owner"},
            {"id": 2, "name": "Admin"},
            {"id": 3, "name": "Member"},
        ],
    )
    op.create_table(
        "users",
        sa.Column("clerk_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clerk_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "family_members",
        sa.Column("family_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"], ["family.id"], name="fk_family_members_family_id"
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name="fk_family_members_role_id"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_family_members_user_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("category", sa.Column("family_id", sa.BigInteger(), nullable=False))
    op.create_foreign_key(
        "fk_category_family_id", "category", "family", ["family_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_category_family_id", "category", type_="foreignkey")
    op.drop_column("category", "family_id")
    op.drop_table("family_members")
    op.drop_table("users")
    op.drop_table("role")
    op.drop_table("family")
    # ### end Alembic commands ###
