"""add family_invitation model

Revision ID: 8ca829c0170e
Revises: 2518006cd411
Create Date: 2026-07-20 08:56:21.265814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8ca829c0170e"
down_revision: Union[str, None] = "2518006cd411"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_invitation",
        sa.Column("family_id", sa.BigInteger(), nullable=False),
        sa.Column("invited_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
            name="fk_family_invitation_family_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name="fk_family_invitation_invited_by_user_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "family",
        sa.Column("max_members", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("family", "max_members")
    op.drop_table("family_invitation")
    # ### end Alembic commands ###
