"""year per budget group

Revision ID: ef6f641febb7
Revises: cf241a834296
Create Date: 2026-07-03 23:36:09.115222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ef6f641febb7"
down_revision: Union[str, None] = "cf241a834296"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_budget_group_year_month"), "budget", type_="unique")
    op.create_unique_constraint(
        "uq_budget_group_month", "budget", ["budget_group_id", "month"]
    )
    op.drop_column("budget", "year")
    op.add_column("budget_group", sa.Column("year", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("budget_group_category_id_key"), "budget_group", type_="unique"
    )
    op.create_unique_constraint(
        "uq_budget_group_category_year", "budget_group", ["category_id", "year"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_budget_group_category_year", "budget_group", type_="unique")
    op.create_unique_constraint(
        op.f("budget_group_category_id_key"),
        "budget_group",
        ["category_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("budget_group", "year")
    op.add_column(
        "budget", sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint("uq_budget_group_month", "budget", type_="unique")
    op.create_unique_constraint(
        op.f("uq_budget_group_year_month"),
        "budget",
        ["budget_group_id", "year", "month"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
